.....F
Failures:

  1) MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Dieta Platos
     Failure/Error: expect(almuerzo.platos).to eq([["Macarrones con salsa de tomate y queso parmesano","1 1/2 cucharón","200"],["Escalope de ternera","1 bistec mediano","100"],["Ensalada básica con zanahoria rallada","guarnición","120"],["Mandarina","1 grande","180"],["Pan de trigo integral","1 rodaja","20"]])

     NoMethodError:
       undefined method `platos' for #<MenuDiet:0x00000000678f40>
     # ./spec/practica6_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 0.00773 seconds (files took 0.17902 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:26 # MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Dieta Platos