......FFFF
Failures:

  1) Dieta ->Probando VCT
     Failure/Error: expect(diet.get_vct()).to eq("V.C.T | %    356'7kcal | ")

     NoMethodError:
       undefined method `get_vct' for #<Dieta:0x00000003708250>
     # ./spec/practica6_spec.rb:37:in `block (2 levels) in <top (required)>'

  2) Dieta ->Probando proteina
     Failure/Error: expect(diet.get_p_proteina()).to eq("10%")

     NoMethodError:
       undefined method `get_p_proteina' for #<Dieta:0x00000003708250>
     # ./spec/practica6_spec.rb:40:in `block (2 levels) in <top (required)>'

  3) Dieta ->Probando grasas
     Failure/Error: expect(diet.get_p_grasas()).to eq("20%")

     NoMethodError:
       undefined method `get_p_grasas' for #<Dieta:0x00000003708250>
     # ./spec/practica6_spec.rb:44:in `block (2 levels) in <top (required)>'

  4) Dieta ->Probando hidratos
     Failure/Error: expect(diet.get_p_hidratos()).to eq("30%")

     NoMethodError:
       undefined method `get_p_hidratos' for #<Dieta:0x00000003708250>
     # ./spec/practica6_spec.rb:48:in `block (2 levels) in <top (required)>'

Finished in 0.00469 seconds (files took 0.14405 seconds to load)
10 examples, 4 failures

Failed examples:

rspec ./spec/practica6_spec.rb:36 # Dieta ->Probando VCT
rspec ./spec/practica6_spec.rb:39 # Dieta ->Probando proteina
rspec ./spec/practica6_spec.rb:43 # Dieta ->Probando grasas
rspec ./spec/practica6_spec.rb:47 # Dieta ->Probando hidratos