.....F..................
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(vector4).not_to be_nil

     NameError:
       undefined local variable or method `vector4' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x00000002d08c78>
     # ./spec/practica6_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 0.00975 seconds (files took 0.14055 seconds to load)
24 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:30 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.