............FF
Failures:

  1) List -> Comprobar si el head de @martes está vacío
     Failure/Error: expect(@martes.head.value).not_to be_nil

     NoMethodError:
       undefined method `head' for nil:NilClass
     # ./spec/practica6_spec.rb:111:in `block (2 levels) in <top (required)>'

  2) List ->Comprobar si esta vacío
     Failure/Error: expect(@lunes.empty?).to eq(false)

     NoMethodError:
       undefined method `empty?' for #<List:0x00000001fb4068>
     # ./spec/practica6_spec.rb:115:in `block (2 levels) in <top (required)>'

Finished in 0.01368 seconds (files took 0.17182 seconds to load)
14 examples, 2 failures

Failed examples:

rspec ./spec/practica6_spec.rb:110 # List -> Comprobar si el head de @martes está vacío
rspec ./spec/practica6_spec.rb:114 # List ->Comprobar si esta vacío