....F..................
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(vector3).not_to be_nil

     NameError:
       undefined local variable or method `vector3' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x0000000348c210>
     # ./spec/practica6_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 0.007 seconds (files took 0.12353 seconds to load)
23 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:25 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.