.F
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(diet).not_to be_nil

     NameError:
       undefined local variable or method `diet' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x0000000379d990>
     # ./spec/practica6_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.00169 seconds (files took 0.14231 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:10 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.