.......F
Failures:

  1) Alimentos Pruebas para la parte Alimentos ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(food).not_to be_nil

     NameError:
       undefined local variable or method `food' for #<RSpec::ExampleGroups::Alimentos::PruebasParaLaParteAlimentos:0x00000002fe5978>
     # ./spec/practica6_spec.rb:41:in `block (3 levels) in <top (required)>'

Finished in 0.00448 seconds (files took 0.11516 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:40 # Alimentos Pruebas para la parte Alimentos ->Debe existir un objeto y estar inicializado.