/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -I/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-support-3.5.0/lib:/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb .......................FFF..................
Failures:

  1) List Pruebas de la parte lista -> Hallar min
     Failure/Error: expect(diet.min).to eq("350")

     NoMethodError:
       undefined method `min' for #<List:0x000000015141d0>
     # ./spec/practica6_spec.rb:131:in `block (3 levels) in <top (required)>'

  2) List Pruebas de la parte lista -> Hallar max
     Failure/Error: expect(diet.max).to eq("356.7")

     NoMethodError:
       undefined method `max' for #<List:0x000000015141d0>
     # ./spec/practica6_spec.rb:134:in `block (3 levels) in <top (required)>'

  3) List Pruebas de la parte lista -> ordenar los vct de menos a mayor
     Failure/Error: expect(diet.sort).to eq(["350", "354", "355", "356.7"])

     NoMethodError:
       undefined method `sort' for #<List:0x000000015141d0>
     # ./spec/practica6_spec.rb:137:in `block (3 levels) in <top (required)>'

Finished in 0.00999 seconds (files took 0.12888 seconds to load)
44 examples, 3 failures

Failed examples:

rspec ./spec/practica6_spec.rb:130 # List Pruebas de la parte lista -> Hallar min
rspec ./spec/practica6_spec.rb:133 # List Pruebas de la parte lista -> Hallar max
rspec ./spec/practica6_spec.rb:136 # List Pruebas de la parte lista -> ordenar los vct de menos a mayor

/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -I/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-support-3.5.0/lib:/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed