...F
Failures:

  1) MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe título como Almuerzo
     Failure/Error: expect(almuerzo.titulo).to eq("Almuerzo")

     NoMethodError:
       undefined method `titulo' for #<MenuDiet:0x00000000d9ee00 @name="Ejemplo">
     # ./spec/practica6_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 0.00708 seconds (files took 0.23623 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:18 # MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe título como Almuerzo