....F
Failures:

  1) List Pruebas de la parte lista ->Debe mostrar una dieta
     Failure/Error: s = @titulo + " (" + @porcentaje + "%" + ")" + "\n"

     NoMethodError:
       undefined method `+' for nil:NilClass
     # ./lib/practica6/dieta.rb:17:in `to_s'
     # ./lib/practica6/lista.rb:22:in `to_s'
     # ./spec/practica6_spec.rb:25:in `block (3 levels) in <top (required)>'

Finished in 0.00569 seconds (files took 0.13736 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:24 # List Pruebas de la parte lista ->Debe mostrar una dieta