....FF
Failures:

  1) Dieta ->Probando descripcion
     Failure/Error: expect(diet.get_descripcion()).to eq("Macarrones\nSpaguetti\n")

     NoMethodError:
       undefined method `get_descripcion' for #<Dieta:0x00000002588868>
     # ./spec/practica6_spec.rb:30:in `block (2 levels) in <top (required)>'

  2) Dieta ->Probando conjunto de platos
     Failure/Error: expect(diet.get_cjto_platos()).to eq("- Macarrones: 1 1/2 cucharón, 200g\n- Spaguetti: 2 cazo, 100g\n")

     NoMethodError:
       undefined method `get_cjto_platos' for #<Dieta:0x00000002588868>
     # ./spec/practica6_spec.rb:34:in `block (2 levels) in <top (required)>'

Finished in 0.00421 seconds (files took 0.11367 seconds to load)
6 examples, 2 failures

Failed examples:

rspec ./spec/practica6_spec.rb:29 # Dieta ->Probando descripcion
rspec ./spec/practica6_spec.rb:33 # Dieta ->Probando conjunto de platos