...F.
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(vector2).not_to be_nil

     NameError:
       undefined local variable or method `vector2' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x000000010e6798>
     # ./spec/practica6_spec.rb:20:in `block (3 levels) in <top (required)>'

Finished in 0.00415 seconds (files took 0.1339 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:19 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado