...........FFFF..........................
Failures:

  1) Dieta Pruebas de la parte dieta vct diet > vct diet2
     Failure/Error: expect(diet > diet2).to eq(true)

     NoMethodError:
       undefined method `>' for #<Dieta:0x000000032a05a0>
     # ./spec/practica6_spec.rb:79:in `block (3 levels) in <top (required)>'

  2) Dieta Pruebas de la parte dieta vct diet !< diet2
     Failure/Error: expect(diet < diet2).to eq(false)

     NoMethodError:
       undefined method `<' for #<Dieta:0x000000032a05a0>
     # ./spec/practica6_spec.rb:82:in `block (3 levels) in <top (required)>'

  3) Dieta Pruebas de la parte dieta vct diet !<= diet2
     Failure/Error: expect(diet <= diet2).to eq(false)

     NoMethodError:
       undefined method `<=' for #<Dieta:0x000000032a05a0>
     # ./spec/practica6_spec.rb:85:in `block (3 levels) in <top (required)>'

  4) Dieta Pruebas de la parte dieta vct diet >= vct diet2
     Failure/Error: expect(diet >= diet2).to eq(true)

     NoMethodError:
       undefined method `>=' for #<Dieta:0x000000032a05a0>
     # ./spec/practica6_spec.rb:88:in `block (3 levels) in <top (required)>'

Finished in 0.01629 seconds (files took 0.14502 seconds to load)
41 examples, 4 failures

Failed examples:

rspec ./spec/practica6_spec.rb:78 # Dieta Pruebas de la parte dieta vct diet > vct diet2
rspec ./spec/practica6_spec.rb:81 # Dieta Pruebas de la parte dieta vct diet !< diet2
rspec ./spec/practica6_spec.rb:84 # Dieta Pruebas de la parte dieta vct diet !<= diet2
rspec ./spec/practica6_spec.rb:87 # Dieta Pruebas de la parte dieta vct diet >= vct diet2