...............F
Failures:

  1) Alimentos Edad Pruebas de la parte alimentos ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(year).not_to be_nil

     NameError:
       undefined local variable or method `year' for #<RSpec::ExampleGroups::Alimentos::Edad::PruebasDeLaParteAlimentos:0x00000001b1e440>
     # ./spec/practica6_spec.rb:78:in `block (4 levels) in <top (required)>'

Finished in 0.00531 seconds (files took 0.10991 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:77 # Alimentos Edad Pruebas de la parte alimentos ->Debe existir un objeto y estar inicializado.