..F
Failures:

  1) MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe name
     Failure/Error: expect(almuerzo.name).not_to be_nil

     NoMethodError:
       undefined method `name' for #<MenuDiet:0x00000002a16768>
     # ./spec/practica6_spec.rb:16:in `block (3 levels) in <top (required)>'

Finished in 0.00393 seconds (files took 0.16909 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:15 # MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe name