....F
Failures:

  1) MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe ingesta
     Failure/Error: expect(almuerzo.ingesta).to eq([[30, 35]])

     NoMethodError:
       undefined method `ingesta' for #<MenuDiet:0x000000023719f8 @name="Ejemplo", @titulo="Almuerzo">
     # ./spec/practica6_spec.rb:23:in `block (3 levels) in <top (required)>'

Finished in 0.00393 seconds (files took 0.13145 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:22 # MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Existe ingesta