.F
Failures:

  1) MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Almuerzo no nil
     Failure/Error: expect(almuerzo).not_to be_nil

     NameError:
       undefined local variable or method `almuerzo' for #<RSpec::ExampleGroups::MenuDiet::PruebaDeLasPartesFundamentalesDeLaClaseDieta:0x0000000205c268>
     # ./spec/practica6_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.00231 seconds (files took 0.15563 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:10 # MenuDiet Prueba de las partes fundamentales de la clase Dieta: -> Almuerzo no nil