..FF
Failures:

  1) Dieta ->Probando titulo
     Failure/Error: expect(diet.get_titulo()).to eq("Media mañana")

     NoMethodError:
       undefined method `get_titulo' for #<Dieta:0x00000002cf37b0>
     # ./spec/practica6_spec.rb:24:in `block (2 levels) in <top (required)>'

  2) Dieta ->Probando porcentaje
     Failure/Error: expect(diet.get_porcentaje()).to eq("(40-45%)")

     NoMethodError:
       undefined method `get_porcentaje' for #<Dieta:0x00000002cf37b0>
     # ./spec/practica6_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.00422 seconds (files took 0.11626 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/practica6_spec.rb:23 # Dieta ->Probando titulo
rspec ./spec/practica6_spec.rb:26 # Dieta ->Probando porcentaje