..F
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(vector).not_to be_nil

     NameError:
       undefined local variable or method `vector' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x000000029003d8>
     # ./spec/practica6_spec.rb:14:in `block (3 levels) in <top (required)>'

Finished in 0.00307 seconds (files took 0.15064 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:13 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.

/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -I/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-support-3.5.0/lib:/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed