....F.
Failures:

  1) List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.
     Failure/Error: expect(letras).not_to be_nil

     NameError:
       undefined local variable or method `letras' for #<RSpec::ExampleGroups::List::PruebasDeLaParteLista:0x000000008a9440>
     # ./spec/practica6_spec.rb:25:in `block (3 levels) in <top (required)>'

Finished in 0.00449 seconds (files took 0.12586 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/practica6_spec.rb:24 # List Pruebas de la parte lista ->Debe existir un objeto y estar inicializado.