........FFF
Failures:

  1) List -> Desayuno del lunes no nil
     Failure/Error: expect(desayuno_L).not_to be_nil

     NameError:
       undefined local variable or method `desayuno_L' for #<RSpec::ExampleGroups::List:0x00000002483620>
     # ./spec/practica6_spec.rb:54:in `block (2 levels) in <top (required)>'

  2) List -> Almuerzo del lunes no nil
     Failure/Error: expect(almuerzo_L).not_to be_nil

     NameError:
       undefined local variable or method `almuerzo_L' for #<RSpec::ExampleGroups::List:0x00000002481780>
     # ./spec/practica6_spec.rb:57:in `block (2 levels) in <top (required)>'

  3) List -> Cena del lunes no nil
     Failure/Error: expect(cena_L).not_to be_nil

     NameError:
       undefined local variable or method `cena_L' for #<RSpec::ExampleGroups::List:0x0000000247e9b8>
     # ./spec/practica6_spec.rb:60:in `block (2 levels) in <top (required)>'

Finished in 0.00819 seconds (files took 0.17242 seconds to load)
11 examples, 3 failures

Failed examples:

rspec ./spec/practica6_spec.rb:53 # List -> Desayuno del lunes no nil
rspec ./spec/practica6_spec.rb:56 # List -> Almuerzo del lunes no nil
rspec ./spec/practica6_spec.rb:59 # List -> Cena del lunes no nil