/home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/spec/practica6_spec.rb:19:in `block (2 levels) in <top (required)>': undefined method `porcent' for #<MenuDiet:0x00000001379528> (NoMethodError)         from /home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/lib/practica6/dieta.rb:17:in `instance_eval'         from /home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/lib/practica6/dieta.rb:17:in `initialize'         from /home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/spec/practica6_spec.rb:5:in `new'         from /home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/spec/practica6_spec.rb:5:in `block in <top (required)>'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `subclass'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'         from /home/ubuntu/workspace/LPP3/tdd-menu-lpp-41-1/practica6/spec/practica6_spec.rb:3:in `<top (required)>'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'         from /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>' /usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -I/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-support-3.5.0/lib:/usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/lib /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed